### ISSUE TITLE
Crashes on login after putting in the otp code

### ISSUE THREAD

**Issue by hurutparittya** [notmarek/BeFake#4]
The script dies right after I put in the otp code during login with the following trace:

Enter otp: XXXXXX
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sircumalot/programming/befake/BeFake/BeFake/__main__.py", line 103, in <module>
    cli()
  File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sircumalot/programming/befake/BeFake/BeFake/__main__.py", line 20, in login
    bf.verify_otp(otp)
  File "/home/sircumalot/programming/befake/BeFake/BeFake/BeFake.py", line 75, in verify_otp
    self.token_info = json.loads(b64decode(res["idToken"].split(".", 3)[1]))
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by nothing4free** [comment]
> The script dies right after I put in the otp code during login with the following trace:
> 
> Enter otp: XXXXXX Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/sircumalot/programming/befake/BeFake/BeFake/**main**.py", line 103, in cli() File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1130, in **call** return self.main(*args, **kwargs) File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/sircumalot/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/home/sircumalot/programming/befake/BeFake/BeFake/**main**.py", line 20, in login bf.verify_otp(otp) File "/home/sircumalot/programming/befake/BeFake/BeFake/BeFake.py", line 75, in verify_otp self.token_info = json.loads(b64decode(res["idToken"].split(".", 3)[1])) File "/usr/lib/python3.10/base64.py", line 87, in b64decode return binascii.a2b_base64(s) binascii.Error: Incorrect padding

getting this as well :(

**Comment by notmarek** [comment]
Fixed by #5
