### ISSUE TITLE
problem with new version

### ISSUE THREAD

**Issue by ALutz273** [notmarek/BeFake#41]
oot@debian:~# **befake parse-friends**
Traceback (most recent call last):
  File "/usr/local/bin/befake", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 146, in parse_friends
    creation_date = friend.profile_picture.get_date().format(date_format)
AttributeError: 'NoneType' object has no attribute 'format'

does anyone else have the same problem? 

root@debian:~# pip list | grep -i befake
BeFake                1.0.1

**Comment by Smart123s** [comment]
Until it gets fixed you can install an older version with
`pip install git+https://github.com/notmarek/BeFake@c3608b0577f5df1180d91ba5cc5182b0ff0b9d79`
