### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by TFKNazGul** [notmarek/BeFake#72]
When i try to login i get this error.

`Enter otp: 895789
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Scripts\befake.exe\__main__.py", line 7, in <module>
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\BeFake\__main__.py", line 52, in login
    bf.verify_otp_vonage(otp)
  File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\BeFake\BeFake.py", line 184, in verify_otp_vonage
    print("Error: " + vonageRes.json()["statusCode"] + vonageRes.json()["message"])
          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str`

**Comment by VxlerieUwU** [comment]
a5574fe919a6dca2c9e94dfbee16261320cb21b2 should fix the issue.

**Comment by Marcus200000001** [comment]
> [a5574fe](https://github.com/notmarek/BeFake/commit/a5574fe919a6dca2c9e94dfbee16261320cb21b2) should fix the issue.

I t

> When i try to login i get this error.
> 
> `Enter otp: 895789 Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Scripts\befake.exe\__main__.py", line 7, in <module> File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__ return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\BeFake\__main__.py", line 52, in login bf.verify_otp_vonage(otp) File "C:\Users\spart\AppData\Local\Programs\Python\Python311\Lib\site-packages\BeFake\BeFake.py", line 184, in verify_otp_vonage print("Error: " + vonageRes.json()["statusCode"] + vonageRes.json()["message"]) ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TypeError: can only concatenate str (not "int") to str`

I think I'm having the same problem, but without the code popping up. it's just a blank white screen

**Comment by NicoWeio** [comment]
@TFKNazGul In the future, try using [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) to make the output more readable.
