### ISSUE TITLE
`parse-friends` and `upload-realmoji` are broken

### ISSUE THREAD

**Issue by cwke** [notmarek/BeFake#78]
`befake parse-friends`      

```
Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jakub\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jakub\anaconda3\Scripts\befake.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\BeFake\__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\BeFake\__main__.py", line 178, in parse_friends
    if friend.profile_picture.exists():
AttributeError: 'NoneType' object has no attribute 'exists'
```

`befake upload-realmoji heartEyes image.jpg`

```
Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jakub\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jakub\anaconda3\Scripts\befake.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\BeFake\__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\BeFake\__main__.py", line 318, in upload_realmoji
    r = bf.upload_realmoji(data, emoji_type=type)
  File "C:\Users\Jakub\anaconda3\lib\site-packages\BeFake\BeFake.py", line 383, in upload_realmoji
    res = self.api_request("put", "person/me/realmojis", data=data, headers={"authorization": self.token})
  File "C:\Users\Jakub\anaconda3\lib\site-packages\BeFake\BeFake.py", line 92, in api_request
    res = self.client.request(
TypeError: httpx._client.Client.request() got multiple values for keyword argument 'headers'
```
The image is located in /data/photos

Windows 11 Version	10.0.22621 Build 22621
Python 3.9.12

**Comment by VxlerieUwU** [comment]
Check if this still happens with 6e457eaf87d42e54f8eab20b18647aacd8cf7741

**Comment by cwke** [comment]
Nop

`befake parse-friends`
```
Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\Scripts\befake.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\__main__.py", line 179, in parse_friends
    creation_date = friend.profile_picture.get_date().format(date_format)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\models\picture.py", line 67, in get_date
    raise Exception(f"Error requesting image: {r.status_code}")
Exception: Error requesting image: 404
```

`befake upload-realmoji heartEyes image.jpg`
```
Traceback (most recent call last):
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\Scripts\befake.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\__main__.py", line 318, in upload_realmoji
    r = bf.upload_realmoji(data, emoji_type=type)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\BeFake.py", line 398, in upload_realmoji
    res = self.api_request("put", "person/me/realmojis", data=data)
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\BeFake\BeFake.py", line 98, in api_request
    res.raise_for_status()
  File "C:\Users\Jakub\anaconda3\envs\scamozzo\lib\site-packages\httpx\_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://mobile.bereal.com/api/person/me/realmojis'
For more information check: https://httpstatuses.com/400
```
