### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [notmarek/BeFake#79]
python3 -m BeFake feed friends
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 378, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 102, in feed
    feed = bf.get_friends_feed()
  File "/usr/local/lib/python3.9/dist-packages/BeFake/BeFake.py", line 238, in get_friends_feed
    res = self.api_request("get", "feeds/friends")
  File "/usr/local/lib/python3.9/dist-packages/BeFake/BeFake.py", line 98, in api_request
    res.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://mobile.bereal.com/api/feeds/friends'
For more information check: https://httpstatuses.com/403

or 

python3 -m BeFake me
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 378, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 79, in me
    user = bf.get_user_info()
  File "/usr/local/lib/python3.9/dist-packages/BeFake/BeFake.py", line 228, in get_user_info
    res = self.api_request("get", "person/me")
  File "/usr/local/lib/python3.9/dist-packages/BeFake/BeFake.py", line 98, in api_request
    res.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://mobile.bereal.com/api/person/me'
For more information check: https://httpstatuses.com/403

i tied refreshing the token and logging in again but so far the same error…

**Comment by ohld** [comment]
The same for me. Probably, they implemented something new.

**Comment by VxlerieUwU** [comment]
On it right now, it appears that the 1.0 update caused some havoc. There will be breaking changes like additional photos soon

**Comment by VxlerieUwU** [comment]
There are now two tokens to manage and store: an access_token for use with mobile.bereal.com and an id_token for use with all firebase-related stuff.

**Comment by sanderDijkxhoorn** [comment]
Is there a temporarily way to manually put in my bearer token?

I got my bearer and refresh token just not sure what is saved in the token.txt

**Comment by sanderDijkxhoorn** [comment]
Wrote a little example code and this works just fine got a temporary solution for myself.

```js
const fs = require('fs');

// User info
let url = "https://mobile.bereal.com/api/feeds/friends-v1";
let AuthroizationToken = "Bearer SussyBakaDon'tTryTOStealMyToken";
let deviceId = "COOL-DEVICE-ID";

// Headers
let headers = {
    "Accept-Encoding": "br;q=1.0, gzip;q=0.9, deflate;q=0.8",
    "Accept-Language": "en-NL;q=1.0, nl-NL;q=0.9",
    "Authorization": AuthroizationToken,
    "bereal-app-language": "en-NL",
    "bereal-app-version": "1.0.1-(9513)",
    "bereal-device-id": deviceId,
    "bereal-device-language": "en",
    "bereal-os-version": "15.4.1",
    "bereal-platform": "iOS",
    "bereal-timezone": "Europe/Amsterdam",
    "bereal-user-agent": "Bereal/1.0.1 (AlexisBarreyat.BeReal; build:9513; iOS 15.4.1) 1.0.0/BRApriKit",
};

// Make a request using native fetch nodejs to the url and log the response (body) which is json to the console
fetch(url, { headers: headers })
    .then((response) => response.json())
    // Save the response (body) to a file called response.json
    .then((json) => fs.writeFileSync('response.json', JSON.stringify(json)))
    .catch((error) => console.error(error));

**Comment by VxlerieUwU** [comment]
token.txt stores your refresh token, but it's gonna be deprecated. You can try my WIP branch at #80 that logs perfectly with vonage if you need a solution right now.

**Comment by sanderDijkxhoorn** [comment]
> token.txt stores your refresh token, but it's gonna be deprecated. You can try my WIP branch at #80 that logs perfectly with vonage if you need a solution right now.

Thanks, I will check it out 👍

**Comment by U14-dev** [comment]
> ```js
> Bearer 
> ```

How did you get your token? I have mine but still got 403 so i guess i'm missing sth

**Comment by ohld** [comment]
For ones who asks yourself how to make the old code work:

0. Update library. Better to clone master brunch and use it locally. Run `git pull` to update it.
1. You need to update tokens

```
from BeFake.BeFake.BeFake import BeFake
bf = BeFake()
bf.legacy_load()
bf.save()
```

2. After that you can simply `bf.load()` as usual. Now you got the login token updated and saved in a new format.
