### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by MMM1706** [notmarek/BeFake#83]
Hi there when I try to login I get following Error:

C:\Users\ASUS\Desktop\MENA\BeReal\BeFake>  python befake.py login +20**********
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\befake.py", line 6, in <module>
    cli(obj={})
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake\__main__.py", line 50, in login
    bf.send_otp_vonage(phone_number)
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake\BeFake.py", line 184, in send_otp_vonage
    if vonageRes.json()["status"] != '0':
KeyError: 'status'

Can somebody help me please? :-)

**Comment by Igor636965736c610a** [comment]
me too

**Comment by Igor636965736c610a** [comment]
![image](https://user-images.githubusercontent.com/102369546/234898426-79ec46cd-0674-4330-a1fd-580de0949b14.png)


Traceback (most recent call last):
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Scripts\befake-script.py", line 33, in <module>
    sys.exit(load_entry_point('BeFake==1.0.1', 'console_scripts', 'befake')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\BeFake\__main__.py", line 21, in login
    bf.send_otp(phone_number)
  File "C:\Users\Igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\BeFake\BeFake.py", line 95, in send_otp
    self.otp_session = res["sessionInfo"]
                       ~~~^^^^^^^^^^^^^^^
KeyError: 'sessionInfo'

**Comment by MMM1706** [comment]
C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake>python BeFake.py login +20**********
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake\BeFake.py", line 11, in <module>
    from .models.realmoji_picture import RealmojiPicture
ImportError: attempted relative import with no known parent package

**Comment by Igor636965736c610a** [comment]
https://github.com/notmarek/BeFake/issues/83#issuecomment-1526078788 
I have the same

**Comment by Igor636965736c610a** [comment]
Okej ludzie znalazłem rozwiązanie! U mnie poprostu zadziałało jak wpisałem zamiast python befake -> python .\befake.py

**Comment by VxlerieUwU** [comment]
Closing.

**Comment by MMM1706** [comment]
> Ok guys I found a solution! For me it just worked as I typed python befake -> python .\befake.py instead

Not working for me … Same error

**Comment by VxlerieUwU** [comment]
> > Ok guys I found a solution! For me it just worked as I typed python befake -> python .\befake.py instead
> 
> Not working for me … Same error

Make sure you are in the same directory with README.md and befake.py. You are inside the wrong directory `C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake` instead of `C:\Users\ASUS\Desktop\MENA\BeReal\BeFake`.

**Comment by MMM1706** [comment]
ok, thank you. Now I got following error: 

C:\Users\ASUS\Desktop\MENA\BeReal\BeFake>python .\befake.py login +20**********
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\befake.py", line 6, in <module>
    cli(obj={})
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake\__main__.py", line 50, in login
    bf.send_otp_vonage(phone_number)
  File "C:\Users\ASUS\Desktop\MENA\BeReal\BeFake\BeFake\BeFake.py", line 185, in send_otp_vonage
    raise Exception(vonageRes.content)
Exception: b'{"statusCode":400,"errorKey":null,"fields":null,"timestamp":"2023-04-28T20:00:49.986Z","requestId":"abbd40a42530a41ea8754f26ab7026bc"}'
