### ISSUE TITLE
AttributeError: 'str' object has no attribute 'write'

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [notmarek/BeFake#86]
I am receiving the following error when I run one of the feed commands on the latest version.
```
python3 -m BeFake feed discovery
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 385, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 137, in feed
    click.echo(f"saving post by {item.user.username}".ljust(50, " "), f"{item.id}")
  File "/usr/local/lib/python3.9/dist-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
AttributeError: 'str' object has no attribute 'write'


python3 -m BeFake feed friends
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 385, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 137, in feed
    click.echo(f"saving post by {item.user.username}".ljust(50, " "), f"{item.id}")
  File "/usr/local/lib/python3.9/dist-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
AttributeError: 'str' object has no attribute 'write'

**Comment by Dooominic** [comment]
i fixed it by adding an exception in lib/python3.10/site-packages/click/utils.py line 299

instead of
` 
file.write(out)  # type: ignore
        file.flush()
`
change it to
`    
    try:
        file.write(out)  # type: ignore
        file.flush()
    except AttributeError:
        pass
   `
I also recommend you set up venv and alter the package in there instead.

**Comment by NicoWeio** [comment]
No need to get so hacky. ;)
With my suggested change, #85 should fix this. You could checkout the PR's branch or apply the changes manually.

**Comment by sanderDijkxhoorn** [comment]
> No need to get so hacky. ;)
> With my suggested change, #85 should fix this. You could checkout the PR's branch or apply the changes manually.


I tried your PR too but I am getting this with anything you run.
Traceback (most recent call last):
  File "/root/BeReal/BeFake/befake.py", line 3, in <module>
    from BeFake.__main__ import cli
  File "/root/BeReal/BeFake/BeFake/__main__.py", line 134
    click.echo(f"saving memory {}".format(item.memory_day))
                                  ^
SyntaxError: f-string: empty expression not allowed

**Comment by NicoWeio** [comment]
Ah, I see you found my [suggested change](https://github.com/notmarek/BeFake/pull/85#discussion_r1181044766) to the PR, which is required for its functioning. :smile: 
Sorry for being a little unclear: Checking out the PR alone won't make it work until my suggested change is incorporated into the PR.

**Comment by henryjac** [comment]
Sorry I didn't realise I had to accept the suggested changes. Have done so now
