### ISSUE TITLE
Receiving Bad Request 400 response when refreshing token

### ISSUE THREAD

**Issue by KoenMangelschots** [notmarek/BeFake#89]
Whenever tokens are attempted to be refreshed after the initial token from the login has expired I am receiving a status 400 response. 

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/BeFake/__main__.py", line 26, in wrapper
    bf.load()
  File "/home/pi/.local/lib/python3.9/site-packages/BeFake/BeFake.py", line 101, in load
    self.refresh_tokens()
  File "/home/pi/.local/lib/python3.9/site-packages/BeFake/BeFake.py", line 250, in refresh_tokens
    raise Exception(res.content)
Exception: b'{"error":"Bad Request","statusCode":400,"message":"Bad Request","errorKey":null,"fields":null,"timestamp":"2023-05-01T11:01:39.013Z","requestId":"aa0389102c50b1b3a59a24ebeb80ca7c"}'
`

**Comment by Smart123s** [comment]
Seems like my PR didn't fix the issue. I'm still getting it. If someone else can confirm this, we could reopen the issue.

**Comment by CyberTimon** [comment]
I also have this issue. +1
